// Code generated by https://github.com/dcaf-mocha/anchor-go. DO NOT EDIT.

package spl_token_swap

import ag_solanago "github.com/gagliardetto/solana-go"

// note: manually changed Swap -> SwapAccount due to conflicts with instruction.Swap
type SwapAccount struct {
	Version        uint8
	IsInitialized  bool
	BumpSeed       uint8
	TokenProgramId ag_solanago.PublicKey
	TokenA         ag_solanago.PublicKey
	TokenB         ag_solanago.PublicKey
	PoolMint       ag_solanago.PublicKey
	TokenAMint     ag_solanago.PublicKey
	TokenBMint     ag_solanago.PublicKey
	PoolFeeAccount ag_solanago.PublicKey
	Fees           Fees
	SwapCurve      SwapCurve
}
