// Code generated by https://github.com/dcaf-mocha/anchor-go. DO NOT EDIT.

package spl_token_swap

import ag_binary "github.com/gagliardetto/binary"

type Fees struct {
	TradeFeeNumerator           uint64
	TradeFeeDenominator         uint64
	OwnerTradeFeeNumerator      uint64
	OwnerTradeFeeDenominator    uint64
	OwnerWithdrawFeeNumerator   uint64
	OwnerWithdrawFeeDenominator uint64
	HostFeeNumerator            uint64
	HostFeeDenominator          uint64
}

type SwapCurve struct {
	CurveType  CurveType
	Calculator [32]uint8
}

type StableCurve struct {
	Amp uint64
}

type OffsetCurve struct {
	TokenBOffset uint64
}

type ConstantProductCurve struct{}

type ConstantPriceCurve struct {
	TokenBPrice uint64
}

type CurveType ag_binary.BorshEnum

const (
	CurveTypeConstantProduct CurveType = iota
	CurveTypeConstantPrice
	CurveTypeStable
	CurveTypeOffset
)

func (value CurveType) String() string {
	switch value {
	case CurveTypeConstantProduct:
		return "ConstantProduct"
	case CurveTypeConstantPrice:
		return "ConstantPrice"
	case CurveTypeStable:
		return "Stable"
	case CurveTypeOffset:
		return "Offset"
	default:
		return ""
	}
}
